# Generated by Django 5.2.1 on 2025-05-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
