# Generated by Django 5.1.6 on 2025-03-13 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, verbose_name='')),
                ('Descripcion', models.TextField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='')),
                ('Apellidos', models.CharField(max_length=100, verbose_name='')),
                ('Email', models.EmailField(max_length=254, verbose_name='')),
                ('Telefono', models.CharField(max_length=15, verbose_name='')),
                ('Fecha_Contratacion', models.DateField(verbose_name='')),
                ('Salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200, verbose_name='')),
                ('Descripcion', models.TextField(verbose_name='')),
                ('Fecha_Inicio', models.DateField(verbose_name='')),
                ('Fecha_Fin', models.DateField(verbose_name='')),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleadoapp.departamento')),
                ('Empleados', models.ManyToManyField(to='Empleadoapp.empleado')),
            ],
        ),
    ]
